# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description for Unit Test"
  lane :test do
    run_tests
  end




  desc "Description for Build IPA "
  lane :beta do
    # increment_build_number
    build_app(scheme: "SwiftDrivingBehavior",
              workspace: "SwiftDrivingBehavior.xcworkspace",
              include_bitcode: true)

  end

  desc "Description for distribute to firebase"
  lane :firebase do 
    firebase_app_distribution(
      app: "1:178573492478:ios:46af9d89d1bf1e34ace5af",
      testers: "terrorize.nut@gmail.com",
      ipa_path: "./SwiftDrivingBehavior.ipa",
      release_notes: "Lots of amazing new features to test out!",
      firebase_cli_path: "/usr/local/bin/firebase"
    )
  end
end


